// <auto-generated />
namespace EMS_DesktopClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EMS_DesktopClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EMS_DesktopClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201906020859591_EMS_DesktopClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
